In [7]:
import numpy as np

X_train = np.array([[1., 1., 1., 1.],
[1., 1., 0., 0.], 
[0., 1., 1., 1.], 
[0., 0., 1., 0.],
[1., 0., 1., 0.]]).reshape(-1,4)

## can NOT select a reordered subset with lists y_train[[1,2]] but with numpy arrays we can!
y_train = np.array([6, 7, 5, 4, 3]) 
test = np.array([0., 1., 1., 1.]) 
# Homegrown KNN

distances_matrix_vec = np.linalg.norm(X_train - test, ord=1, axis=1)
print(f"distances are: {distances_matrix_vec}")
k_nearest_neighbor_indices = np.argsort(distances_matrix_vec)[:4]
print(f"k_nearest_neighbor_indices are : {k_nearest_neighbor_indices}")
print(f"classes of nearest neighbors are: {y_train[k_nearest_neighbor_indices]}")
class_knn_1 = y_train[k_nearest_neighbor_indices][0]
class_knn_4 = y_train[k_nearest_neighbor_indices][0:4].mean()

print(f"KNN with n = 1: {class_knn_1}")
print(f"KNN with n = 4: {class_knn_4}")

distances are: [1. 3. 0. 2. 3.]
k_nearest_neighbor_indices are : [2 0 3 1]
classes of nearest neighbors are: [5 6 4 7]
KNN with n = 1: 5
KNN with n = 4: 5.5


In [10]:
import numpy as np
X=np.array([1, 2, 1, 2])
w=np.array([4,-2,-4, 8])
eta = .05
y = 4
gradient = np.dot(X.dot(w)-y,X)
w = w - eta * gradient 
print(w)

[ 3.6 -2.8 -4.4  7.2]


In [12]:
import numpy as np
X=np.array([1, 2, 1, 2])
w=np.array([2,-1,-2, 4])
y = 4
#####
yhat = np.dot(X,w)
MSE =  np.square(yhat-y)
#####
print(MSE)

4


In [95]:
import numpy as np
X1=np.array([1, 2, 1, 2])
X2=np.array([1, 1, 2, 2])
w=np.array([4,-2,-4, 8])
eta = .05
y1 = 4
y2 = 3
###

# BATCH #
w0 = w - eta * np.dot(np.dot(X1,w)-y1,X1) - eta * np.dot(np.dot(X2,w)-y2,X2)

# SOCHASTIC #
w =w- eta * np.dot(np.dot(X1,w)-y1,X1)
w =w- eta * np.dot(np.dot(X2,w)-y2,X2)
###
print(w0)
print(w)

[ 3.25 -3.15 -5.1   6.5 ]
[ 3.43 -2.97 -4.74  6.86]


In [130]:
import numpy as np
X1=np.array([1, 2, 1, 2])
X2=np.array([1, 1, 2, 2])
w=np.array([2,-1,-2, 4])
alpha = 0.1
y1 = 4
y2 = 3
#####
ridge_loss = 1/2  * (np.square(np.dot(X1,w)-y1) + np.square(np.dot(X2,w)-y2)) + (alpha *.5 *np.sum(np.square(w[1:])))
lasso_loss = 1/2  * (np.square(np.dot(X1,w)-y1) + np.square(np.dot(X2,w)-y2)) + (alpha * np.sum(np.abs(w[1:])))
#####
print(f"Ridge Loss {ridge_loss.sum()}")
print(f"Lasso Loss {lasso_loss.sum()}")

Ridge Loss 5.05
Lasso Loss 4.7


In [54]:
import pandas as pd
import numpy as np

vocabulary = ["bad", "good", "very"]

# Document by term matrix
doc_per_term= np.array([[0, 1, 0 ],
[0, 1, 1],
[1, 1, 0],
[1, 0, 1],
[1, 1, 2]])
# y_train
# 0 for Ham and 1 for spam
class_per_doc= np.array([0,1,1,0,1])
display(pd.DataFrame(np.c_[class_per_doc, doc_per_term], index = ["d1", "d2","d3", "d4", "d5"],
columns = ["Class"]+ vocabulary))

## Learn the Naïve Bayes Classification
##
##
model_priors = np.bincount(class_per_doc)/ len(class_per_doc)
print(f"model_priors: {model_priors}")
print (np.sum(doc_per_term[class_per_doc==0,:],axis=0))
#=========================================================#
# Place your code between here #
# Please adapt the following code to accomplish this task #
#
# Calculate Pr(w_i|ham) aka ham class conditionals
model_data_given_ham = (1 + np.sum(doc_per_term[class_per_doc==0],axis=0))/(np.sum(doc_per_term[class_per_doc==0]) + len(vocabulary))
# Calculate Pr(w_i|ham) aka SPAM class conditionals
model_data_given_spam = (1 + np.sum(doc_per_term[class_per_doc==1],axis=0))/(np.sum(doc_per_term[class_per_doc==1]) + len(vocabulary))
# #
# When asked to copy/paste your code in the homework #
# submission quiz, only submit the code you added #
# (or modified) between the comment blocks #
#==========================================================#

# Test document terms are:
# bad, good, very
d6 = [1, 1, 1] #TEST DOCUMENT
display(pd.DataFrame([d6], index = ["d3"], columns = vocabulary))

## Naïve Bayes Classification
## Likelihood
## Applying the Unigram Language Model
# Calculate Posterior Probabilities using the learnt Naive Bayes Model
#
print(f"likelihood Pr(d6|ham): {np.prod(np.power(model_data_given_ham, d6))}")
print(f"likelihood Pr(d6|SPAM): {np.prod(np.power(model_data_given_spam, d6))}")

pr_ham = np.prod(np.power(model_data_given_ham, d6)) * model_priors[0]
pr_spam = np.prod(np.power(model_data_given_spam, d6))* model_priors[1]
print(f"unnormalized Pr(D6|ham)*Pr(ham) is : {pr_ham:7.5f}")
print(f"unnormalized Pr(D6|SPAM)*Pr(SPAM) is : {pr_spam:7.5f}")

print(f"Posterior Probabilities in % is: Pr(Ham|D6) is : {100*pr_ham/(pr_spam+pr_ham):7.0f}")
print(f"Posterior Probabilities in % is: Pr(SPAM|D6) is : {100*pr_spam/(pr_spam+pr_ham):7.0f}")

Class  bad  good  very
d1      0    0     1     0
d2      1    0     1     1
d3      1    1     1     0
d4      0    1     0     1
d5      1    1     1     2

model_priors: [0.4 0.6]
[1 1 1]


bad  good  very
d3    1     1     1

likelihood Pr(d6|ham): 0.037037037037037035
likelihood Pr(d6|SPAM): 0.03606311044327573
unnormalized Pr(D6|ham)*Pr(ham) is : 0.01481
unnormalized Pr(D6|SPAM)*Pr(SPAM) is : 0.02164
Posterior Probabilities in % is: Pr(Ham|D6) is :      41
Posterior Probabilities in % is: Pr(SPAM|D6) is :      59


In [62]:
import numpy as np
w1 = [-1, 2, 3]
w2 = [-7,-4, 1]
X = [1,1,2]
#modify here
d1 = np.dot(X,w1)
d2 = np.dot(X,w2)
#######
print(f"score for w1 is : {d1:7.5f}")
print(f"score for w2 is : {d2:7.5f}")

score for w1 is : 7.00000
score for w2 is : -9.00000


In [131]:
print(f'{np.round((- np.log(1-.5) - np.log(.3))/2, 3)}')

0.949


In [144]:
import numpy as np

X = np.array([[1,1,0], [1,1,3], [1,2,4], [1,1,2]]).reshape(-1,3)
w = np.array([1,-2,1])
y = np.array([0, 1, 0, 1])

p_hat = 1/ (1 + np.exp(-np.dot(X,w)))

CXE_loss = (-1/X.shape[0]) * np.sum((y * np.log(p_hat)) + (1-y) * np.log(1-p_hat))
print(f"{CXE_loss:5.2f}")

 0.52


In [83]:
from sklearn.datasets import load_diabetes
from sklearn.pipeline import make_pipeline
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
from sklearn.feature_selection import SelectPercentile, f_regression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
import pandas as pd

dataset_name = "Diabetes"
ds = load_diabetes()
X_train, X_test, y_train, y_test = train_test_split(ds.data, ds.target,
                                                    random_state=0)

#=========================================================#
# Place your code between here                            #
# Please adapt the following code to accomplish this task #
params = {'knn__n_neighbors':list(range(1,16)),
         'knn__weights': ['distance','uniform']}
pipeline = Pipeline([
    ('knn',KNeighborsRegressor())
])
grid = GridSearchCV(pipeline,params,cv=5,verbose=1,n_jobs=-1,refit=True,scoring="neg_mean_absolute_error")
grid.fit(X_train,y_train)
#                                                          #
# When asked to copy/paste your code in the homework       # 
# submission quiz, only submit the code you added          #
# (or modified) between the comment blocks                 #
#==========================================================#

n, wgt = grid.best_params_['knn__n_neighbors'], grid.best_params_['knn__weights']

# experiment table of results
# del experimentLog
try: experimentLog 
except : experimentLog = pd.DataFrame(columns=[ "CVTrain_MAE", "Test_MAE", "Dataset", 
                                               "Exp_Desc", "Model", "Hyperparams"])
experimentLog.loc[len(experimentLog)] =[f"{-grid.best_score_:10.3f}", 
                                        f"{-grid.score(X_test, y_test):10.3f}", 
                                        dataset_name, "std", "KNN",
                                        f"weighted={wgt}, k_nn={n}"]
display(experimentLog)

Fitting 5 folds for each of 30 candidates, totalling 150 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  38 tasks      | elapsed:    1.0s
[Parallel(n_jobs=-1)]: Done 150 out of 150 | elapsed:    1.2s finished
/usr/local/lib/python3.7/site-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


CVTrain_MAE    Test_MAE   Dataset Exp_Desc Model                 Hyperparams
0      44.177      46.525  Diabetes      std   KNN  weighted=distance, k_nn=11

In [82]:
import sklearn
sorted(sklearn.metrics.SCORERS.keys())

['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'brier_score_loss',
 'completeness_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'max_error',
 'mutual_info_score',
 'neg_log_loss',
 'neg_mean_absolute_error',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'normalized_mutual_info_score',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'recall',
 'recall_macro',
 'recall_micro',
 'recall_samples',
 'recall_weighted',
 'roc_auc',
 'v_measure_score']